/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.solsoftware.interfaces;

import javax.swing.JFileChooser;

/**
 *
 * @author Alexis29
 */
public class BienInmueble extends javax.swing.JFrame {

    /**
     * Creates new form BienInmueble
     */
    public BienInmueble() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPersona = new javax.swing.JPanel();
        lblTipoBien = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblCatalogo = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblNombArtic = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtNombreBien = new javax.swing.JTextField();
        txtCodigoBarra = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        bntTipoBien = new javax.swing.JComboBox();
        spnCantidad = new javax.swing.JSpinner();
        bntAtras = new javax.swing.JButton();
        bntGuardBien = new javax.swing.JButton();
        bntAgregarImag = new javax.swing.JButton();
        bntAgregarCatalogo = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntBuscar = new javax.swing.JButton();
        bntLimpiar = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        bntTipoBien1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPersona.setBackground(new java.awt.Color(255, 255, 255));
        panelPersona.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro De Bienes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        lblTipoBien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTipoBien.setText("Tipo del bien");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo.setText("Codigo Barra");

        lblCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCantidad.setText("Cantidad");

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/solsoftware/Imagenes/sello instituto logo.png"))); // NOI18N

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripcion");

        lblCatalogo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCatalogo.setText("Catalogo");

        lblUbicacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUbicacion.setText("Ubicacion");

        lblImagen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblImagen.setText("Imagen");

        lblNombArtic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombArtic.setText("Nombre del Articulo");

        txtNombreBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBienActionPerformed(evt);
            }
        });

        txtCodigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarraActionPerformed(evt);
            }
        });

        txtUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUbicacionActionPerformed(evt);
            }
        });

        bntTipoBien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobiliario", "Herramienta", "Equipo" }));
        bntTipoBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTipoBienActionPerformed(evt);
            }
        });

        bntAtras.setText("Atras");
        bntAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAtrasActionPerformed(evt);
            }
        });

        bntGuardBien.setText("Guardar");
        bntGuardBien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardBienActionPerformed(evt);
            }
        });

        bntAgregarImag.setText("Abrir");
        bntAgregarImag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarImagActionPerformed(evt);
            }
        });

        bntAgregarCatalogo.setText("Abrir");
        bntAgregarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarCatalogoActionPerformed(evt);
            }
        });

        bntEditar.setText("Editar");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        bntBuscar.setText("Buscar");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });

        bntLimpiar.setText("Limpiar");
        bntLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLimpiarActionPerformed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstado.setText("Estado");

        bntTipoBien1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Funcional", "Por Reparar" }));
        bntTipoBien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTipoBien1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPersonaLayout = new javax.swing.GroupLayout(panelPersona);
        panelPersona.setLayout(panelPersonaLayout);
        panelPersonaLayout.setHorizontalGroup(
            panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPersonaLayout.createSequentialGroup()
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCatalogo)
                                .addComponent(lblCantidad)
                                .addComponent(lblDescripcion)
                                .addComponent(lblNombArtic, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCodigo)
                                .addComponent(lblTipoBien)
                                .addComponent(lblEstado)
                                .addComponent(lblImagen))
                            .addGroup(panelPersonaLayout.createSequentialGroup()
                                .addComponent(lblUbicacion)
                                .addGap(82, 82, 82)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombreBien, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                            .addComponent(txtDescripcion)
                                            .addComponent(txtCodigoBarra)
                                            .addComponent(bntAgregarImag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(bntTipoBien1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bntTipoBien, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bntAgregarCatalogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPersonaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(bntAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(bntEditar)
                        .addGap(59, 59, 59)
                        .addComponent(bntLimpiar)
                        .addGap(49, 49, 49)
                        .addComponent(bntGuardBien, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntBuscar)
                .addGap(6, 6, 6))
            .addGroup(panelPersonaLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(lblIcono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPersonaLayout.setVerticalGroup(
            panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonaLayout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombArtic)
                        .addGap(18, 18, 18)
                        .addComponent(lblCantidad)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripcion))
                    .addGroup(panelPersonaLayout.createSequentialGroup()
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntTipoBien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))
                        .addGap(18, 18, 18)
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntTipoBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoBien))
                        .addGap(18, 18, 18)
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUbicacion))
                        .addGap(18, 18, 18)
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntAgregarCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCatalogo))))
                .addGap(18, 18, 18)
                .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPersonaLayout.createSequentialGroup()
                        .addComponent(bntAgregarImag, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(panelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntGuardBien)
                            .addComponent(bntAtras)
                            .addComponent(bntEditar)
                            .addComponent(bntLimpiar))
                        .addGap(55, 55, 55))
                    .addGroup(panelPersonaLayout.createSequentialGroup()
                        .addComponent(lblImagen)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntTipoBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTipoBienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntTipoBienActionPerformed

    private void bntGuardBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardBienActionPerformed

    }//GEN-LAST:event_bntGuardBienActionPerformed

    private void bntAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtrasActionPerformed

    }//GEN-LAST:event_bntAtrasActionPerformed

    private void txtUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUbicacionActionPerformed

    private void txtCodigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarraActionPerformed

    private void txtNombreBienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBienActionPerformed

    private void bntAgregarImagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarImagActionPerformed
        

    }//GEN-LAST:event_bntAgregarImagActionPerformed

    private void bntAgregarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAgregarCatalogoActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntBuscarActionPerformed

    private void bntLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntLimpiarActionPerformed

    private void bntTipoBien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTipoBien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntTipoBien1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BienInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BienInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BienInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BienInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BienInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAgregarCatalogo;
    private javax.swing.JButton bntAgregarImag;
    private javax.swing.JButton bntAtras;
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntGuardBien;
    private javax.swing.JButton bntLimpiar;
    private javax.swing.JComboBox bntTipoBien;
    private javax.swing.JComboBox bntTipoBien1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCatalogo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombArtic;
    private javax.swing.JLabel lblTipoBien;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JPanel panelPersona;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTextField txtCodigoBarra;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombreBien;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
